install: python ci.py install
before_build: python ci.py before_build
build_script: python ci.py build_script
after_build: python ci.py after_build
before_test: python ci.py before_test
test_script: python ci.py test_script
after_test: python ci.py after_test
on_success: python ci.py on_success
on_failure: python ci.py on_failure
on_finish: python ci.py on_finish
