environment:
  matrix:
    # - BOOST_VERSION_MINOR: 63
    #   BUILD_SHARED_LIBS: ON
    - BOOST_VERSION_MINOR: 63
      BUILD_SHARED_LIBS: OFF
    - BOOST_VERSION_MINOR: 62
      BUILD_SHARED_LIBS: OFF
    - BOOST_VERSION_MINOR: 61
      BUILD_SHARED_LIBS: OFF
    - BOOST_VERSION_MINOR: 60
      BUILD_SHARED_LIBS: OFF

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

install: python build.py before-install install
before_build: python build.py before-build
build_script: python build.py build
after_build: python build.py after_build
before_test: python build.py before_test
test_script: python build.py test
after_test: python build.py after-test
on_success: python build.py after-success
on_failure: python build.py after-failure
on_finish: #python build.py on_finish
