################################################################################
#                                                                              #
#          Appveyor "continuous integration" configuration file                #
#                                                                              #
################################################################################

# Environment variables. Every item in the sequence (delimited by dashes) gives
# us another build in the build matrix.
environment:
  matrix:
    - BOOST_VERSION_MINOR: 63
      BUILD_SHARED_LIBS: ON
    - BOOST_VERSION_MINOR: 63
      BUILD_SHARED_LIBS: OFF
    - BOOST_VERSION_MINOR: 60
      BUILD_SHARED_LIBS: ON
    - BOOST_VERSION_MINOR: 60
      BUILD_SHARED_LIBS: OFF


# Build with VS2015
image: Visual Studio 2015

# Build both 32 and 64 bit versions.
platform:
  - x86
  - x64

# MSVC configurations.
configuration:
  - Debug
  - Release

before_build:
  # Appveyor has the following boost libraries installed:
  # 1.63.0 (C:\Libraries\boost_1_63_0)
  # 1.62.0 (C:\Libraries\boost_1_62_0)
  # 1.60.0 (C:\Libraries\boost_1_60_0)
  # 1.59.0 (C:\Libraries\boost_1_59_0)
  # 1.58.0 (C:\Libraries\boost_1_58_0)
  # 1.56.0 (C:\Libraries\boost)
  # See: https://www.appveyor.com/docs/installed-software/#languages-libraries-frameworks
  # Need to adjust the PATH to make these DLLs visible to our test executables.

  # BOOST_VERSION_MINOR is set in the environment matrix in this YAML file.
  - set BOOST_ROOT=C:\Libraries\boost_1_%BOOST_VERSION_MINOR%_0

  # APPVEYOR_BUILD_FOLDER is the path where yaml-archive is cloned to.
  - set BUILD_DIR=%APPVEYOR_BUILD_FOLDER%\build

  # PLATFORM is the value set by the platform key in this YAML file.
  # CONFIGURATION is the value set by the configuration key in this YAML file.
  # BUILD_SHARED_LIBS is set in the environment matrix in this YAML file.
  - |
    if %PLATFORM%==x86 (
        if %BUILD_SHARED_LIBS%==ON (
            set BOOST_LIBS=%BOOST_ROOT%\lib32-msvc-14.0
            set "PATH=%PATH%;%BOOST_LIBS%"
            set "PATH=%PATH%;%BUILD_DIR%\src\%CONFIGURATION%"
        )
        set "GENERATOR=Visual Studio 14 2015"
    )
  - |
    if %PLATFORM%==x64 (
        if %BUILD_SHARED_LIBS%==ON (
            set BOOST_LIBS=%BOOST_ROOT%\lib64-msvc-14.0
            set "PATH=%PATH%;%BOOST_LIBS%"
            set "PATH=%PATH%;%BUILD_DIR%\src\%CONFIGURATION%"
        )
      set "GENERATOR=Visual Studio 14 2015 Win64"
    )

  # Configure the project.
  - mkdir %BUILD_DIR%
  - cd %BUILD_DIR%
  - cmake %APPVEYOR_BUILD_FOLDER% -G"%GENERATOR%" -DBOOST_ROOT=%BOOST_ROOT% -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DBUILD_SHARED_LIBS=%BUILD_SHARED_LIBS%

build_script:
  # Build the library and the test executables for CTest.
  - cmake --build %BUILD_DIR% --target ALL_BUILD --config %CONFIGURATION%

test_script:
  # Run all unit tests.
  - ctest -C %CONFIGURATION% --output-on-failure
