sudo: required
dist: trusty

language: cpp

os:
  - linux
  - osx

cache:
  apt: true
compiler:
  - clang
  - g++

addons:
  apt:
    sources:
      - boost-latest
    packages:
      - libboost-all-dev
      - cmake

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ctest
