dist: trusty
language: cpp
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake

env:
  - BOOST_VERSION_MINOR=63 BUILD_SHARED_LIBS=ON  CMAKE_BUILD_TYPE=Debug
  # - BOOST_VERSION_MINOR=60 BUILD_SHARED_LIBS=ON  CMAKE_BUILD_TYPE=Debug
  - BOOST_VERSION_MINOR=63 BUILD_SHARED_LIBS=OFF CMAKE_BUILD_TYPE=Debug
  # - BOOST_VERSION_MINOR=60 BUILD_SHARED_LIBS=OFF CMAKE_BUILD_TYPE=Debug
  - BOOST_VERSION_MINOR=63 BUILD_SHARED_LIBS=ON  CMAKE_BUILD_TYPE=Release
  # - BOOST_VERSION_MINOR=60 BUILD_SHARED_LIBS=ON  CMAKE_BUILD_TYPE=Release
  - BOOST_VERSION_MINOR=63 BUILD_SHARED_LIBS=OFF CMAKE_BUILD_TYPE=Release
  # - BOOST_VERSION_MINOR=60 BUILD_SHARED_LIBS=OFF CMAKE_BUILD_TYPE=Release

before_install: python build.py before-install
install: python build.py install
before_script: python build.py before-build
script: python build.py build after-build before-test test after-test
after_success: python build.py after-success
after_failure: python build.py after-failure
after_script: #python ci.py after_script

