dist: trusty
language: cpp
compiler:
  - gcc
  # - clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      # - llvm-toolchain-trusty-3.9
      # - boost-latest
    packages:
      # - gcc-5
      - g++-5
      # - clang-3.9
      - cmake

env:
  - CXX=g++   BOOST_VERSION_MINOR=63 BUILD_SHARED_LIBS=ON  CMAKE_BUILD_TYPE=Debug
  # - CXX=g++   BOOST_VERSION_MINOR=62 BUILD_SHARED_LIBS=ON  CMAKE_BUILD_TYPE=Debug
  # - CXX=g++   BOOST_VERSION_MINOR=61 BUILD_SHARED_LIBS=ON  CMAKE_BUILD_TYPE=Debug
  # - CXX=g++   BOOST_VERSION_MINOR=60 BUILD_SHARED_LIBS=ON  CMAKE_BUILD_TYPE=Debug
  # - CXX=g++-5 BOOST_VERSION_MINOR=63 BUILD_SHARED_LIBS=ON  CMAKE_BUILD_TYPE=Debug
  # - CXX=g++-5 BOOST_VERSION_MINOR=62 BUILD_SHARED_LIBS=ON  CMAKE_BUILD_TYPE=Debug
  # - CXX=g++-5 BOOST_VERSION_MINOR=61 BUILD_SHARED_LIBS=ON  CMAKE_BUILD_TYPE=Debug
  # - CXX=g++-5 BOOST_VERSION_MINOR=60 BUILD_SHARED_LIBS=OFF CMAKE_BUILD_TYPE=Debug
  # - CXX=g++   BOOST_VERSION_MINOR=63 BUILD_SHARED_LIBS=OFF CMAKE_BUILD_TYPE=Debug
  # - CXX=g++   BOOST_VERSION_MINOR=62 BUILD_SHARED_LIBS=OFF CMAKE_BUILD_TYPE=Debug
  # - CXX=g++   BOOST_VERSION_MINOR=61 BUILD_SHARED_LIBS=OFF CMAKE_BUILD_TYPE=Debug
  # - CXX=g++   BOOST_VERSION_MINOR=60 BUILD_SHARED_LIBS=OFF CMAKE_BUILD_TYPE=Debug
  # - CXX=g++-5 BOOST_VERSION_MINOR=63 BUILD_SHARED_LIBS=OFF CMAKE_BUILD_TYPE=Debug
  # - CXX=g++-5 BOOST_VERSION_MINOR=62 BUILD_SHARED_LIBS=OFF CMAKE_BUILD_TYPE=Debug
  # - CXX=g++-5 BOOST_VERSION_MINOR=61 BUILD_SHARED_LIBS=OFF CMAKE_BUILD_TYPE=Debug
  # - CXX=g++-5 BOOST_VERSION_MINOR=60 BUILD_SHARED_LIBS=OFF CMAKE_BUILD_TYPE=Debug
  # - CXX=g++   BOOST_VERSION_MINOR=63 BUILD_SHARED_LIBS=ON  CMAKE_BUILD_TYPE=Release
  # - CXX=g++   BOOST_VERSION_MINOR=62 BUILD_SHARED_LIBS=ON  CMAKE_BUILD_TYPE=Release
  # - CXX=g++   BOOST_VERSION_MINOR=61 BUILD_SHARED_LIBS=ON  CMAKE_BUILD_TYPE=Release
  # - CXX=g++   BOOST_VERSION_MINOR=60 BUILD_SHARED_LIBS=ON  CMAKE_BUILD_TYPE=Release
  # - CXX=g++-5 BOOST_VERSION_MINOR=63 BUILD_SHARED_LIBS=ON  CMAKE_BUILD_TYPE=Release
  # - CXX=g++-5 BOOST_VERSION_MINOR=62 BUILD_SHARED_LIBS=ON  CMAKE_BUILD_TYPE=Release
  # - CXX=g++-5 BOOST_VERSION_MINOR=61 BUILD_SHARED_LIBS=ON  CMAKE_BUILD_TYPE=Release
  # - CXX=g++-5 BOOST_VERSION_MINOR=60 BUILD_SHARED_LIBS=OFF CMAKE_BUILD_TYPE=Release
  # - CXX=g++   BOOST_VERSION_MINOR=63 BUILD_SHARED_LIBS=OFF CMAKE_BUILD_TYPE=Release
  # - CXX=g++   BOOST_VERSION_MINOR=62 BUILD_SHARED_LIBS=OFF CMAKE_BUILD_TYPE=Release
  # - CXX=g++   BOOST_VERSION_MINOR=61 BUILD_SHARED_LIBS=OFF CMAKE_BUILD_TYPE=Release
  # - CXX=g++   BOOST_VERSION_MINOR=60 BUILD_SHARED_LIBS=OFF CMAKE_BUILD_TYPE=Release
  # - CXX=g++-5 BOOST_VERSION_MINOR=63 BUILD_SHARED_LIBS=OFF CMAKE_BUILD_TYPE=Release
  # - CXX=g++-5 BOOST_VERSION_MINOR=62 BUILD_SHARED_LIBS=OFF CMAKE_BUILD_TYPE=Release
  # - CXX=g++-5 BOOST_VERSION_MINOR=61 BUILD_SHARED_LIBS=OFF CMAKE_BUILD_TYPE=Release
  # - CXX=g++-5 BOOST_VERSION_MINOR=60 BUILD_SHARED_LIBS=OFF CMAKE_BUILD_TYPE=Release

before_install: python ci.py before_install
install: python ci.py install
before_script: python ci.py before_script
script: python ci.py script
after_success: python ci.py after_success
after_failure: python ci.py after_failure
after_script: python ci.py after_script
